name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Debug - Show secrets (for troubleshooting)
      run: |
        echo "Docker Hub username: ${{ secrets.DOCKER_HUB_USERNAME != '' && '***' || 'NOT SET' }}"
        echo "Docker Hub token: ${{ secrets.DOCKER_HUB_TOKEN != '' && '***' || 'NOT SET' }}"
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  # Explicit path
        push: ${{ github.ref == 'refs/heads/main' }}  # Only push on main branch
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-image-name:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-image-name:${{ github.sha }}